name: EA
channels:
  - conda-forge
dependencies:
  - pyviz/label/earthsim::holoviews
  - pyviz/label/earthsim::bokeh
  - imageio
  - ipywidgets
  - matplotlib
  - numpy
  - panel
  - param
  - pillow
  - pydensecrf
  - requests
