name: EA
channels:
  - conda-forge
dependencies:
  - python
  - bokeh
  - pydensecrf
  - Pillow
  - scipy
  - matplotlib
  - ipython
  - jupyter  
  - holoviews
  - datashader
  - param
  - geoviews
  - earthsim
  - numpy
  - xarray
  - geopandas
  - notebook
  - lancet
  - colorcet
  - datashader
  - param
  - parambokeh
  - paramnb
  - pyct
  - holoviews
  - geoviews
  - panel
  - x264
  - zeromq
  - libkml
  - scipy
  - nbsmoke
